version: '3.9'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: halyk
    restart: unless-stopped
volumes:
  postgres_data: